### PR TITLE
1.19 compiles

### PR DESCRIPTION
**Pull request by Dolphin2Point1**
With these changes 1.19 compiles and the server boots up. I haven't tested whether the gameplay works as I currently do not have anyone to test it with. I based this PR on #8, so that's where Hugman's commits came from.

### CODE REVIEW

**Review by SmellyModder — CHANGES_REQUESTED** [review]
Thanks so much! 😄 
I haven't had time to work on this project, unfortunately. 
Everything looks pretty good, there is just some general code-style stuff that got messed up.
Stuff like `for (...)` became `for(...)`
The codecs were ```
instance -> { return instance.group(```, but now they are ```instance -> instance.group(```

**Comment by Dolphin2Point1** [comment]
I think I got all of it, but if there's any more code formatting you'd like me to change, just tell me.

**Comment by Dolphin2Point1** [comment]
@haykam821 can you also confirm the translations are correct

**Comment by haykam821** [comment]
The game and game type translation keys seem correct to me.

**Review by SmellyModder — CHANGES_REQUESTED** [review]
Ok, so I guess I wasn't clear enough about the `for (...)` becoming `for(...)` stuff, sorry.
I meant there are many areas in the code where the space between keywords and parenthesis got removed. You can see these pretty easily in the diff.
I can do another review to highlight all the areas if you want.

**Comment by Dolphin2Point1** [comment]
I think that should be all of it, but if you find anything else, please put it in your review so I can see what lines to change.

**Review by SmellyModder — APPROVED** [review]

**Pull request merged**
