### PR TITLE
🌱 Made Murder Mystery compile on 1.17

### PR DESCRIPTION
**Pull request by Hugman76**
I also replaced some classes with record classes to ease with coding.
Some style changes have been applied, by it's been done automatically by my IDE, so I suggest you run through it again if you wish to revert those...

### CODE REVIEW

**Review by Gegy — APPROVED** [review]

**Comment by SmellyModder** [comment]
I'm sorry for my lack of inactivity here, and I will get to looking over this PR soon.
If I see any style issues, I'll just fix them myself.
Thanks for doing the hard work here :)

**Comment by haykam821** [comment]
Games and game types should be translated using `game.<namespace>.<path>` and `gameType.<namespace>.<path>` respectively as well. Currently, the game type translation uses an incorrect key:

https://github.com/NucleoidMC/Murder-Mystery/blob/20cc38aa00d763d3cb0e93b379e15b2a6be66052/src/main/resources/data/murder_mystery/lang/en_us.json#L2-L4

Because of this change, overriding the name to use a translation is now unnecessary:

https://github.com/NucleoidMC/Murder-Mystery/blob/20cc38aa00d763d3cb0e93b379e15b2a6be66052/src/main/resources/data/murder_mystery/games/mansion.json#L3
https://github.com/NucleoidMC/Murder-Mystery/blob/20cc38aa00d763d3cb0e93b379e15b2a6be66052/src/main/resources/data/murder_mystery/games/metro.json#L3

**Comment by SmellyModder** [comment]
That sounds simple to fix, and I'll fix it if nobody does first.
> Because of this change, overriding the name to use a translation is now unnecessary:

Not sure what you mean by this. Are you just saying the `translation` keys in games aren't needed anymore?

**Comment by haykam821** [comment]
Yes, since game names in Plasmid 0.5 default to `game.<namespace>.<path>`.

**Pull request closed without merging**
